import { CirclePlus } from "lucide-react";
import { useState } from "react";

type question = {
  id: Number;
  title: String;
  desc: String;
};

export const QuestionSection = () => {
  const [questionId, setQuestionId] = useState<Number>(-1);
  const questions: question[] = [
    {
      id: 1,
      title: "How does the app work?",
      desc: "The app uses natural language processing and machine learning algorithms to analyze the content of your article or video. It then identifies the key themes, keywords, and phrases and generates multiple headlines based on that information. The generated headlines are designed to be catchy, attention-grabbing, and optimized for the specific platform you are publishing on.",
    },
    {
      id: 2,
      title: "What platforms can I use the headline generator app for?",
      desc: "The headline generator app supports multiple platforms including YouTube, Medium, Indie Hackers, and Reddit. You can choose the platform you want to publish on and the app will generate headlines optimized for that platform.",
    },
    {
      id: 3,
      title: "How do I use the app?",
      desc: "To use the app, you simply need to provide a brief description ofyour article or video. The app will then analyze the description andgenerate multiple headlines. You can choose the headline you likebest or use them as inspiration to create your own headline.",
    },
    {
      id: 4,
      title: "Can I customize the headlines generated by the app?",
      desc: "Yes, you can customize the headlines generated by the app. The app allows you to edit and tweak the headlines to better suit your needs.",
    },
    {
      id: 5,
      title: "Is the app free?",
      desc: "Yes, you get 5 free credits once you login to try out the app",
    },
  ];

  const handleClick = (id: any) => {
    if (questionId === id) {
      setQuestionId(-1);
      return;
    }
    setQuestionId(id);
  };

  return (
    <section className="w-[60%] flex flex-col justify-center items-center gap-8 my-16">
      <h1 className="text-white text-4xl font-bold">
        Frequently Asked Questions
      </h1>
      <h3 className="text-lg text-center text-zinc-300">
        Everything you need to know about the product and billing.
      </h3>
      <div className="w-full flex flex-col gap-6 mt-6">
        {questions.map((question, index) => (
          <div
            key={index}
            onClick={() => handleClick(question.id)}
            className="flex flex-col gap-2 cursor-pointer"
          >
            <div className="flex justify-between text-white text-lg">
              <h1 className="">{question.title}</h1>
              <CirclePlus />
            </div>
            <h1
              className={
                questionId === question.id ? "text-zinc-500" : "hidden"
              }
            >
              {question.desc}
            </h1>
          </div>
        ))}
      </div>
    </section>
  );
};
